# Generated by Django 4.2.6 on 2023-10-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategories',
            name='explicit_url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
